# Generated by Django 2.0.4 on 2018-05-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='THardwareControl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hardware_name', models.CharField(db_column='HARDWARE_NAME', max_length=15)),
                ('class_field', models.CharField(db_column='CLASS', max_length=40)),
                ('vendor', models.CharField(blank=True, db_column='VENDOR', max_length=100, null=True)),
                ('model', models.CharField(db_column='MODEL', max_length=50)),
                ('serial_number', models.CharField(blank=True, db_column='SERIAL_NUMBER', max_length=30, null=True)),
                ('department', models.CharField(db_column='DEPARTMENT', max_length=50)),
                ('administrator', models.CharField(blank=True, db_column='ADMINISTRATOR', max_length=50, null=True)),
                ('os', models.CharField(blank=True, db_column='OS', max_length=20, null=True)),
                ('name_cpu', models.CharField(blank=True, db_column='NAME_CPU', max_length=20, null=True)),
                ('cpu_capacity', models.FloatField(blank=True, db_column='CPU_CAPACITY', null=True)),
                ('ram_capacity', models.IntegerField(blank=True, db_column='RAM_CAPACITY', null=True)),
                ('harddisc_capacity', models.IntegerField(blank=True, db_column='HARDDISC_CAPACITY', null=True)),
                ('date_purchase', models.DateTimeField(blank=True, db_column='DATE_PURCHASE', null=True)),
                ('date_discard', models.DateTimeField(blank=True, db_column='DATE_DISCARD', null=True)),
                ('net_access', models.NullBooleanField(db_column='NET_ACCESS')),
                ('office_software', models.CharField(blank=True, db_column='OFFICE_SOFTWARE', max_length=20, null=True)),
                ('antivirus_software', models.CharField(blank=True, db_column='ANTIVIRUS_SOFTWARE', max_length=20, null=True)),
                ('stock_taking_date', models.DateTimeField(blank=True, db_column='STOCK_TAKING_DATE', null=True)),
                ('external_support', models.NullBooleanField(db_column='EXTERNAL_SUPPORT')),
                ('remarks', models.TextField(blank=True, db_column='REMARKS', null=True)),
            ],
        ),
    ]
